SELECT
	 ',@'+c.COLUMN_NAME+' '+c.DATA_TYPE+(CASE WHEN c.CHARACTER_MAXIMUM_LENGTH IS NULL THEN '' ELSE '('+CAST(c.CHARACTER_MAXIMUM_LENGTH AS VARCHAR)+')' END)
	,',@'+c.COLUMN_NAME+' = x.'+c.COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS c
WHERE c.TABLE_NAME = 'CCATS_ProviderData_Detail'